- src/Microweber/Providers/FormsManager.php
- src/Microweber/Utils/MailSender.php
I updated FormsManager to allow for different subjects on form submission for admin and auto response.  Also updated MailSender to allow specifying "from" for email messages - which is now used in FormsManager to make the email to admin appear to come from the email address submitted by the user.
> Additional fixes for Issue #353

- bootstrap/autoload.php
- composer.json
- phpunit.xml
- src/Microweber/Providers/OptionManager.php
- src/Microweber/tests/ConfigFileTest.php
- src/Microweber/tests/DbTest.php
- src/Microweber/tests/LogTest.php
- src/Microweber/tests/TestCase.php
- src/Microweber/tests/TestConfigFile.php
HI,
I had grabbed microweber for my own use - play with it a bit, see if it does what I needed - and tripped over some problems when I tried to speed up its test suite.
Biggest problem I found was that a few tests were falsely passing (I think 8) when they should have failed.
I also found a lot of tautological $this->assertTrue(true, {error message} ) calls that didn't seem to be really checking anything.  
I've tried to fix those tests as best as I understand them - when I modified them as a result of this cleanup, I was probably writing characterisation tests (as is, versus should be).
> Fix test suite

- userfiles/modules/logo/admin.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microweber/microweber/389)
> commits  for #387

- composer.json
- composer.lock
- src/Microweber/Controllers/DefaultController.php
- src/Microweber/MicroweberServiceProvider.php
- src/Microweber/Providers/Database/Utils.php
- src/Microweber/Providers/DatabaseManager.php
- src/Microweber/Providers/MenuManager.php
- src/Microweber/Providers/UrlManager.php
- src/Microweber/Traits/QueryFilter.php
- src/Microweber/Utils/Adapters/Cache/CacheStore.php
- src/Microweber/Utils/Adapters/Cache/LaravelCache.php
- src/Microweber/Utils/ClassLoader.php
- userfiles/modules/menu/index.php
- userfiles/modules/site_stats/functions.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microweber/microweber/401)
> Update to Laravel 5.4 

- src/Microweber/MicroweberServiceProvider.php
this **PR** refactors **microweberServiceProvider** , it extracted the logic to small functions and removes some dead code and also modify indentation .
> [Dev] Refactor microweberServiceProvider

- .htaccess
Hello, this PR restricts direct web access to composer dependencies and other stuff.
> Restricted direct access to packagist dependencies from the web

- src/Microweber/Controllers/InstallController.php
> Fix error when installing microweber to localhost with table preffix

- src/Microweber/Providers/FormsManager.php
- userfiles/modules/comments/privacy_settings.php
- userfiles/modules/contact_form/functions.php
- userfiles/modules/contact_form/index.php
- userfiles/modules/contact_form/privacy_settings.php
- userfiles/modules/contact_form/settings.php
- userfiles/modules/contact_form/templates/dark.php
- userfiles/modules/contact_form/templates/default.php
- userfiles/modules/custom_fields/index.php
- userfiles/modules/newsletter/privacy_settings.php
- userfiles/modules/settings/group/users.php
- userfiles/modules/shop/cart/index.php
- userfiles/modules/users/terms/index.php
Proposed updates for issue #602
> Privacy settings update #602

- src/Microweber/Install/Schema/Base.php
- src/Microweber/Providers/UserManager.php
- userfiles/modules/microweber/css/admin.css
- userfiles/modules/settings/group/users.php
- userfiles/modules/users/edit_user.php
- userfiles/modules/users/manage.php
- userfiles/modules/video/admin.php
- userfiles/modules/video/config.php
- userfiles/modules/video/functions.php
- userfiles/modules/video/index.php
- userfiles/modules/video/templates/default.php
Optional setting to require admin approval after a user registers before they can login.
Also fixes for last login time and preventing login if set to inactive; and the addition of a login count.
> Registration approval

- userfiles/modules/microweber/toolbar/editor_tools/imageeditor/index.php
Updated userfiles\modules\microweber\toolbar\editor_tools\imageeditor\index.php to allow image title and alt text to be updated to fix issue #626
> Fix image title & alt text issue #626

- src/Microweber/Providers/ShopManager.php
Fix: Now display the currency symbol of any country and added Brazil currency number format.
> Fix display currency symbol of other country and added BRL number format.

- src/Microweber/Utils/Files.php
https://huntr.dev/users/aybulgin has fixed the Arbitrary File Upload vulnerability 🔨. Think you could fix a vulnerability like this?
Get involved at https://huntr.dev/
Q | A
Version Affected | ALL
Bug Fix | YES
Original Pull Request | https://github.com/418sec/microweber/pull/1
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/packagist/microweber/microweber/1/README.md
This could result in execution of malicious content in case there's a nested Java server to show to the user's the images uploaded.
This fix added the .jsp extension to file uploader blacklist mechanism.
This "arbitrary file upload" while true doesn't allow the attacker to execute the php webshells uploaded, however if there's another Java server used for any other user image admisitration it …
> Security Fix for Arbitrary File Upload - huntr.dev

- src/MicroweberPackages/Install/Resources/views/install.php
'notifications' was incorrectly spelled 'notifiactions'
> install.php: typo

- src/MicroweberPackages/Order/resources/views/admin/notifications/new_order.blade.php
- src/MicroweberPackages/Order/resources/views/admin/orders/order_card.blade.php
- userfiles/modules/admin/notifications/notif_order.php
> payment method name show in view order option

- README.md
Hi!
alwaysdata also provides a 1click installation process. I thought it would be interesting for users to have a choice there.
Maybe the docs also deserve a chapter on installation page to list any Cloud Provider having such a quick installation process, or even a documentation page about deploying Microweber... Let me know!
Thank you
> Add alwaysdata 1click install link

- CONTRIBUTING.md
- src/MicroweberPackages/User/Http/Controllers/UserRegisterController.php
return message sent as a response when a user wants to register on the system. When a user registers then after registration they will not get any confirmation message. I fixed this and now the user will get the confirmation message from the controller as a condition-based return.
I noticed some more improvement, After merged this I'll do those also.
> return message send at registration

- userfiles/modules/cookie_notice/admin.php
In cookies module panel toggle position does not work based on user settings like left,right, center .
> Panel Toggle Position issue fixed in cookie_notice module 

- docs/testing.md
This PR updates the testing documentation with:
- Clear guidance against parallel Dusk testing
- Performance optimization tips
- Improved troubleshooting section
These changes help prevent common testing pitfalls while maintaining testing best practices.
> Update testing documentation

- Modules/Restore/Tests/RestoreTest.php
This skips the zip import test since the sample file contains no importable content, which is expected behavior.
> Skip zip import test for empty content

- Modules/Offer/Tests/Unit/OfferModelTest.php
This PR adds comprehensive integration tests for the Offer model, covering:
- Creation and deletion
- Price formatting
- Expiry date handling
- Price retrieval methods
> Add integration tests for Offer model

- Modules/Coupons/Tests/Unit/CouponServiceTest.php
- Modules/Coupons/database/factories/CouponFactory.php
This PR adds:
- New CouponService tests
- Coupon factory
- Improved test coverage
> Add comprehensive tests for Coupons module

- Modules/Embed/Tests/Unit/EmbedModuleSettingsFilamentTest.php
- Modules/TextType/Tests/Unit/TextTypeModuleSettingsFilamentTest.php
- Modules/Video/Tests/Unit/VideoModuleSettingsFilamentTest.php
This PR adds automated tests for the Video module settings form, covering all form fields and their persistence.
> Add comprehensive tests for Video module

- Modules/Coupons/Models/CartCouponLog.php
- Modules/Coupons/Models/Coupon.php
- Modules/Coupons/Services/CouponService.php
- Modules/Coupons/Tests/Unit/CouponApplyTest.php
- Modules/Coupons/Tests/Unit/CouponServiceTest.php
- Modules/Coupons/Tests/Unit/CouponValidationTest.php
- Modules/Coupons/database/migrations/2025_04_04_132753_add_valid_dates_to_coupons_table.php
- Modules/Coupons/database/migrations/2025_04_04_132753_add_valid_dates_to_coupons_table.php.bak
- Modules/Coupons/database/migrations/2025_04_04_140101_add_product_restrictions_to_coupons.php
- modules/Coupons/Database/Migrations/2025_04_04_145900_add_columns_to_cart_coupon_logs.php
This PR implements:
- Proper coupon application logging
- Database schema updates
- Fixed test cases
- Discount capping validation
> Fix coupon logging and validation

- Modules/Profile/Tests/Unit/ProfileModuleTest.php
This PR adds comprehensive unit tests for the Profile module, including:
- Two-factor authentication trait verification
- Model fillable fields validation
- Configuration file checks
> Improve Profile module test coverage

- Modules/Audio/Filament/AudioModuleSettings.php
- Modules/Audio/Tests/Unit/AudioModuleSettingsFilamentTest.php
- Updated file upload validation rules
- Improved test assertions
- Added temporary file cleanup verification
> Fix audio module validation and tests

- Modules/Billing/database/migrations/2025_05_31_000005_create_subscription_plans_groups_table.php
- Modules/Comments/database/migrations/2024_01_02_000000_create_comments_table.php
- Modules/Menu/database/migrations/2022_07_04_130209_create_menus_table.php
- Modules/Menu/database/migrations/2024_07_04_130209_add_mega_menu_column_to_menus_table.php
- Modules/Payment/database/migrations/2024_07_23_00001_create_payment_providers_table.php
- Modules/Payment/database/migrations/2024_07_25_00007_create_payments_table.php
- Modules/Tag/database/migrations/2014_01_07_073615_create_tagged_table.php
Fixed several migration issues:
- Corrected duplicate table creation in comments migration
- Ensured all migrations use proper anonymous class syntax
- Verified all database schema changes
> Fix migration issues

- Modules/ImageRollover/Tests/Unit/ImageRolloverFrontendTest.php
- Modules/ImageRollover/Tests/Unit/ImageRolloverModuleSettingsFilamentTest.php
- Modules/ImageRollover/Tests/Unit/ImageRolloverModuleTest.php
This PR adds thorough unit tests for the ImageRollover module, covering:
- Core module properties
- Initialization
- Template configuration
Tests avoid external dependencies for reliability.
> Add comprehensive unit tests for ImageRollover module
